### ISSUE TITLE
Can't build package: "signal: killed"

### ISSUE THREAD

**Issue by mholt** [blevesearch/segment#5]
Running:

    $ go build github.com/blevesearch/segment

I get:

    go build github.com/blevesearch/segment: /usr/local/go/pkg/tool/linux_amd64/6g: signal: killed

I'm running on 64-bit Linux. Any idea what might be happening?

**Comment by mholt** [comment]
Oh. Apparently it takes ~1 GB of memory to build this package. My machine only had 512; raising the memory limit fixed it.

**Comment by mschoch** [comment]
Thanks for reporting this.  The insane memory requirements are tied to the new Ragel generated FSM.  It's fast at runtime but slow compilation and this high memory requirement are side-effects.

I'm considering defaulting to a slower FSM with fewer tradeoffs.  Then letting developers enable the fast one with a build tag.

Would you be in favor of something like that?

**Comment by mholt** [comment]
That'd be cool, especially if the developer can choose which to use. (However, if that complicates your code base too much, then I wouldn't worry about it.)

**Comment by xieyuschen** [comment]
> Thanks for reporting this. The insane memory requirements are tied to the new Ragel generated FSM. It's fast at runtime but slow compilation and this high memory requirement are side-effects.
> 
> I'm considering defaulting to a slower FSM with fewer tradeoffs. Then letting developers enable the fast one with a build tag.
> 
> Would you be in favor of something like that?

Hi @mschoch , could I check with you how did you make the code change for this one, I cannot find the commit about it. Could you help me?
Regards
